# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12simple_video.proto\x12\x0csimple_video\"\x9c\x01\n\x0cVideoMessage\x12)\n\x05\x66rame\x18\x01 \x01(\x0b\x32\x18.simple_video.VideoFrameH\x00\x12*\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x18.simple_video.ClientInfoH\x00\x12*\n\x06status\x18\x03 \x01(\x0b\x32\x18.simple_video.StatusInfoH\x00\x42\t\n\x07\x63ontent\"L\n\nVideoFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"4\n\nClientInfo\x12\x13\n\x0b\x63lient_type\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\".\n\nStatusInfo\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2_\n\x12VideoStreamService\x12I\n\x0bStreamVideo\x12\x1a.simple_video.VideoMessage\x1a\x1a.simple_video.VideoMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOMESSAGE']._serialized_start=37
  _globals['_VIDEOMESSAGE']._serialized_end=193
  _globals['_VIDEOFRAME']._serialized_start=195
  _globals['_VIDEOFRAME']._serialized_end=271
  _globals['_CLIENTINFO']._serialized_start=273
  _globals['_CLIENTINFO']._serialized_end=325
  _globals['_STATUSINFO']._serialized_start=327
  _globals['_STATUSINFO']._serialized_end=373
  _globals['_VIDEOSTREAMSERVICE']._serialized_start=375
  _globals['_VIDEOSTREAMSERVICE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
