# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simple_video_pb2 as simple__video__pb2


class VideoStreamServiceStub(object):
    """簡化的影像串流服務
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVideo = channel.stream_stream(
                '/simple_video.VideoStreamService/StreamVideo',
                request_serializer=simple__video__pb2.VideoMessage.SerializeToString,
                response_deserializer=simple__video__pb2.VideoMessage.FromString,
                )


class VideoStreamServiceServicer(object):
    """簡化的影像串流服務
    """

    def StreamVideo(self, request_iterator, context):
        """雙向串流：傳送端發送影像，接收端獲取影像
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVideo,
                    request_deserializer=simple__video__pb2.VideoMessage.FromString,
                    response_serializer=simple__video__pb2.VideoMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simple_video.VideoStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoStreamService(object):
    """簡化的影像串流服務
    """

    @staticmethod
    def StreamVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/simple_video.VideoStreamService/StreamVideo',
            simple__video__pb2.VideoMessage.SerializeToString,
            simple__video__pb2.VideoMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
